-- MySQL Script generated by MySQL Workbench
-- Mon May 27 14:33:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema follow_up
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema follow_up
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `follow_up` DEFAULT CHARACTER SET utf8 ;
USE `follow_up` ;

-- -----------------------------------------------------
-- Table `follow_up`.`partners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `follow_up`.`partners` ;

CREATE TABLE IF NOT EXISTS `follow_up`.`partners` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`employee_id`));


-- -----------------------------------------------------
-- Table `follow_up`.`legal_forms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `follow_up`.`legal_forms` ;

CREATE TABLE IF NOT EXISTS `follow_up`.`legal_forms` (
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`title`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `follow_up`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `follow_up`.`clients` ;

CREATE TABLE IF NOT EXISTS `follow_up`.`clients` (
  `siret` CHAR(14) NOT NULL,
  `companyName` VARCHAR(255) NOT NULL,
  `legalFormTitle` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`siret`),
  INDEX `idx_legalFormTitle` (`legalFormTitle` ASC) VISIBLE,
  UNIQUE INDEX `siret_UNIQUE` (`siret` ASC) VISIBLE,
  CONSTRAINT `fk_client_legalForm`
    FOREIGN KEY (`legalFormTitle`)
    REFERENCES `follow_up`.`legal_forms` (`title`));


-- -----------------------------------------------------
-- Table `follow_up`.`managers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `follow_up`.`managers` ;

CREATE TABLE IF NOT EXISTS `follow_up`.`managers` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`employee_id`));


-- -----------------------------------------------------
-- Table `follow_up`.`audit_periods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `follow_up`.`audit_periods` ;

CREATE TABLE IF NOT EXISTS `follow_up`.`audit_periods` (
  `period_id` INT NOT NULL AUTO_INCREMENT,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  PRIMARY KEY (`period_id`));


-- -----------------------------------------------------
-- Table `follow_up`.`type_audits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `follow_up`.`type_audits` ;

CREATE TABLE IF NOT EXISTS `follow_up`.`type_audits` (
  `label` VARCHAR(255) NOT NULL,
  `nomination` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`label`),
  UNIQUE INDEX `label_UNIQUE` (`label` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `follow_up`.`mission_audits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `follow_up`.`mission_audits` ;

CREATE TABLE IF NOT EXISTS `follow_up`.`mission_audits` (
  `audit_id` INT NOT NULL AUTO_INCREMENT,
  `auditDate` DATE NOT NULL,
  `fee` DECIMAL(10,2) NULL DEFAULT NULL,
  `typeAuditLabel` VARCHAR(255) NOT NULL,
  `period_id` INT NOT NULL,
  `siret` CHAR(14) NOT NULL,
  PRIMARY KEY (`audit_id`),
  INDEX `idx_typeAuditLabel` (`typeAuditLabel` ASC) VISIBLE,
  INDEX `idx_period_id` (`period_id` ASC) VISIBLE,
  INDEX `idx_siret` (`siret` ASC) VISIBLE,
  CONSTRAINT `fk_missionAudit_typeAudit`
    FOREIGN KEY (`typeAuditLabel`)
    REFERENCES `follow_up`.`type_audits` (`label`),
  CONSTRAINT `fk_missionAudit_period`
    FOREIGN KEY (`period_id`)
    REFERENCES `follow_up`.`audit_periods` (`period_id`),
  CONSTRAINT `fk_missionAudit_client`
    FOREIGN KEY (`siret`)
    REFERENCES `follow_up`.`clients` (`siret`));


-- -----------------------------------------------------
-- Table `follow_up`.`partners_mission_audits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `follow_up`.`partners_mission_audits` ;

CREATE TABLE IF NOT EXISTS `follow_up`.`partners_mission_audits` (
  `partner_id` INT NOT NULL,
  `audit_id` INT NOT NULL,
  PRIMARY KEY (`partner_id`, `audit_id`),
  INDEX `idx_audit_id` (`audit_id` ASC) VISIBLE,
  CONSTRAINT `fk_partnerMissionAudit_partner`
    FOREIGN KEY (`partner_id`)
    REFERENCES `follow_up`.`partners` (`employee_id`),
  CONSTRAINT `fk_partnerMissionAudit_audit`
    FOREIGN KEY (`audit_id`)
    REFERENCES `follow_up`.`mission_audits` (`audit_id`));


-- -----------------------------------------------------
-- Table `follow_up`.`managers_mission_audits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `follow_up`.`managers_mission_audits` ;

CREATE TABLE IF NOT EXISTS `follow_up`.`managers_mission_audits` (
  `manager_id` INT NOT NULL,
  `audit_id` INT NOT NULL,
  PRIMARY KEY (`manager_id`, `audit_id`),
  INDEX `idx_audit_id` (`audit_id` ASC) VISIBLE,
  CONSTRAINT `fk_managerMissionAudit_manager`
    FOREIGN KEY (`manager_id`)
    REFERENCES `follow_up`.`managers` (`employee_id`),
  CONSTRAINT `fk_managerMissionAudit_audit`
    FOREIGN KEY (`audit_id`)
    REFERENCES `follow_up`.`mission_audits` (`audit_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
